name:          Hrvatska verzija priručnika za pisanje HTML-a i CSS-a od @mdo
description:   Standardi za razvoj fleksibilnog, pouzdanog i održivog koda u HTML-u i CSS-u.
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
